// Updated 09-Feb-22

const fiatSymbols = [
  'SDR/USD',
  'CNY/USD',
  'EUR/USD',
  'JPY/USD',
  'GBP/USD',
  'KRW/USD',
  'INR/USD',
  'CAD/USD',
  'HKD/USD',
  'AUD/USD',
]

module.exports = {
  port: 8532,
  metricsPort: 8533,
  sentry: '', // sentry dsn (https://sentry.io/ - error reporting service)
  slack: {
    // for incident alarm (e.g. exchange shutdown)
    channel: '#bot-test',
    url: '',
  },
  cryptoProvider: {
    adjustTvwap: { symbols: [] },
    fallbackPriority: ["coinGecko", "binance", "kraken", "kucoin", "huobi", "bitfinex"],
    coinGecko: {
      interval: 30 * 1000,
      symbols: [
        "BTC/USD",
        "ETH/USD",
        "BNB/USD",
        "USDT/USD",
        "USDC/USD",
        "BUSD/USD",
        "DAI/USD",
        "XRP/USD",
        "DOGE/USD",
        "ADA/USD",
        "MATIC/USD",
        "DOT/USD",
        "LTC/USD",
        "STETH/USD",
        "OKB/USD",
        "SHIB/USD",
        "SOL/USD",
        "TRX/USD",
        "UNI/USD",
        "AVAX/USD",
        "LINK/USD",
        "ETC/USD",
        "TON/USD",
        "XMR/USD",
        "XLM/USD",
        "ALGO/USD",
        "QNT/USD",
        "FIL/USD",
        "NEAR/USD",
        "VET/USD",
        "FLOW/USD",
        "APE/USD",
        "ICP/USD",
        "EGLD/USD",
        "CHZ/USD",
        "EOS/USD",
        "XCN/USD",
        "XTZ/USD",
        "LDO/USD",
        "SAND/USD",
        "THETA/USD",
        "AAVE/USD",
        "AXS/USD",
        "MANA/USD",
        "MIOTA/USD",
        "MKR/USD",
        "CAKE/USD",
        "APT/USD",
        "XEC/USD",
        "ZEC/USD",
        "KLAY/USD",
        "GT/USD",
        "NEO/USD",
        "AR/USD",
        "DASH/USD",
        "FTM/USD",
        "GRT/USD",
        "SNX/USD",
        "MINA/USD",
        "CRV/USD",
        "NEXO/USD",
        "XRD/USD",
        "GMX/USD",
        "BAT/USD",
        "ZIL/USD",
        "ENS/USD",
        "1INCH/USD",
        "HNT/USD",
        "XDC/USD",
        "FXS/USD",
        "STX/USD",
        "CVX/USD",
        "ENJ/USD",
        "IMX/USD",
        "LRC/USD",
        "DCR/USD",
        "DFI/USD",
        "TFUEL/USD",
        "AMP/USD",
        "COMP/USD",
        "NXM/USD",
        "DYDX/USD",
        "ATOM/USD",
        "LUNA/USD",
        "CRO/USD",
        "OSMO/USD",
        "RUNE/USD",
        "EVMOS/USD",
        "KAVA/USD",
        "OKT/USD",
        "ANKR/USD",
        "KDA/USD",
        "LUNC/USD",
        "USTC/USD",
        "INJ/USD",
        "SCRT/USD",
        "JUNO/USD",
        "CTK/USD",
        "STARS/USD",
        "AKT/USD"
      ],
    },
    binance: {
      symbols: ['LUNA/USDT', 'LUNA/BUSD', 'BTC/USDT', 'BTC/BUSD', 'ETH/USDT', 'ETH/BUSD', 'BUSD/USDT'],
    },
    kraken: {
      symbols: ['USDT/USD', 'USDC/USD', 'BUSD/USD'],
    },
    kucoin: {
      symbols: ['LUNA/USDT', 'BTC/USDT', 'ETH/USDT'],
    },
    huobi: {
      symbols: ['LUNA/USDT', 'BTC/USDT', 'ETH/USDT'],
    },
    bitfinex: {
      symbols: ['USDT/USD', 'BTC/USDT', 'ETH/USDT'],
    },
  },
  fiatProvider: {
    fallbackPriority: ['exchangerate', 'frankfurter', 'fer'],
    // https://exchangerate.host/
    exchangerate: {
      symbols: fiatSymbols,
      interval: 60 * 1000,
      timeout: 5000,
    },
    // https://fer.ee/
    fer: {
      symbols: fiatSymbols.filter((f) => !f.includes('SDR')),
      interval: 60 * 1000,
      timeout: 5000,
    },
    // https://www.frankfurter.app/docs/
    frankfurter: {
      symbols: fiatSymbols.filter((f) => !f.includes('SDR')),
      interval: 60 * 1000,
      timeout: 5000,
    },
  },
}
